# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QxeBZpFiuQrOfajem4EsOpJXvoGqu8V
"""



import streamlit as st
from streamlit_javascript import st_javascript
import psycopg2 # El conector para Postgres

js_code = """
const detectExit = () => {
  document.addEventListener('mouseleave', (event) => {
    if (event.clientY <= 0) {
      // Enviamos una señal al servidor de que el usuario intentó salir
      window.parent.postMessage({type: 'exit_intent', data: true}, '*');
    }
  });
};
detectExit();
"""

# Configuración de conexión (Asegúrate de que coincidan con tu pgAdmin)
def get_connection():
    return psycopg2.connect(
        dbname="hotel_db",
        user="postgres",       # Usuario por defecto
        password="Salmo91", # Cambia esto por tu contraseña de Postgres
        host="localhost",
        port="5432"
    )

st.title("🏨 Hotel Unknown AI - Dashboard")

with st.form("registro_abandono"):
    nombre = st.text_input("Nombre del Prospecto")
    email = st.text_input("Email")
    habitacion = st.selectbox("Interés", ["Suite Ejecutiva", "Habitación Doble", "Penthouse","Habitacion Sencilla"])
    precio = 500 if "Penthouse" in habitacion else 200

    if st.form_submit_button("Simular Abandono de Carrito"):
        try:
            conn = get_connection()
            cur = conn.cursor()
            cur.execute("""
                INSERT INTO reservas_abandonadas (cliente_nombre, cliente_email, tipo_habitacion, precio_total)
                VALUES (%s, %s, %s, %s)
            """, (nombre, email, habitacion, precio))
            conn.commit()
            cur.close()
            conn.close()
            st.warning(f"⚠️ Evento capturado: {nombre} dejó el proceso. Datos guardados en pgAdmin.")
        except Exception as e:
            st.error(f"Error de conexión: {e}")
